name: Update NEU Repo Files

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/NotEnoughUpdates/NotEnoughUpdates-REPO.git src/main/resources/neu
