name: Update NEU Repo Files

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate
        run: |
          git config --local user.email action@github.com
          git config --local user.name "Github Action"
          
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Clone
        run: |
          git clone https://github.com/NotEnoughUpdates/NotEnoughUpdates-REPO.git src/main/resources/neu
          
      - name: Commit
        run: |
          git remote set-url origin https://github.com/Hytilities/SkyFlipper.git
          git add --all
          git commit -m "Automated Action"
